site_name: DevOps Portfolio. | DevOps Portfolio
site_url: https://nikolasht1.github.io/
repo_url: https://github.com  # Ensure your profile matches

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Projects & Case Studies:
    - Infrastructure as Code: iac.md
    - CI/CD Pipelines: cicd.md
    - Containerization (K8s): containers.md
  - Observability & Monitoring: monitoring.md
  - Resume: resume.md
