name: Deploy Azure-Oxide Website to GitHub Pages

on:
  # Triggers the workflow on push events targeting the default branch
  push:
    branches: ["main" , "master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queue.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we are just hosting a static HTML site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages Environment
        uses: actions/configure-pages@v5

      - name: Upload Static Web Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository contents (where your index.html lives)
          path: '.'

      - name: Deploy Artifacts to GitHub Pages Live Engine
        id: deployment
        uses: actions/deploy-pages@v4
